services:
  api:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: my-pitwall-api
    restart: unless-stopped
    ports:
      - "5170:5170"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5170
