<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\MyPitwall.Application\MyPitwall.Application.csproj" />
    <ProjectReference Include="..\MyPitwall.Contracts\MyPitwall.Contracts.csproj" />
  </ItemGroup>

</Project>
