<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyPitwall.Application\MyPitwall.Application.csproj" />
    <ProjectReference Include="..\MyPitwall.Contracts\MyPitwall.Contracts.csproj" />
    <ProjectReference Include="..\MyPitwall.Infrastructure\MyPitwall.Infrastructure.csproj" />
  </ItemGroup>

</Project>
